### ISSUE TITLE
Wget links for VGG*.npy.

### ISSUE THREAD

**Issue by why-not** [machrisaa/tensorflow-vgg#10]
It's a pain to create an account etc to just download that file. Also a wget link will be better since I am guessing folks are downloading this to a server instead of to local machine.

**Comment by machrisaa** [comment]
I don't want to put it to my own servers. Any suggestions for free storage?

**Comment by machrisaa** [comment]
You don't need to create account to download the npy file. At the moment I am not going to create a web service for getting the file. So this issue will be closed.
