### ISSUE TITLE
Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by aryopg** [machrisaa/tensorflow-vgg#19]
I'm getting an error from this line of code : 
`red, green, blue = tf.split(3, 3, rgb_scaled)`

I saw some tutorials that says that i need to change the parameter order, i changed it into : 

`red, green, blue = tf.split(rgb_scaled, 3, 3)`

And i got this error instead : 

`Expected int32, got list containing Tensors of type '_Message' instead.`

Thanks.

**Comment by aryopg** [comment]
I've solved this, it's about the version of the tensorflow. Sorry to bother

**Comment by micklexqg** [comment]
@aryopg , how do you solved it? I came across the same error.

**Comment by machrisaa** [comment]
The `tf.split` was updated in the v1.0.0 to be `tf.split(value, num_or_size_splits, axis)`. (see the detail [here](https://github.com/tensorflow/tensorflow/blob/v1.0.0-rc1/RELEASE.md).

And not just the `tf.split`, there are lots of methods have their signatures changed. So you need to update your Tensorflow or modify the code to the pre-v1 version. You can check the last commit to see the changes [here](https://github.com/machrisaa/tensorflow-vgg/commit/e189a5ea1328c2ad3cc84d916945cbe87bc46e7e#diff-3e40d6d822ca2bd5f10af4b695eb62a0R35)
