### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by phongnhhn92** [machrisaa/tensorflow-vgg#23]
Hello, i am tf beginner. When i look at your code, i didnt see any instruction of how to training vgg from scratch or fine tuning from specified weights. Would you mind showing me how to do with your code ? Thanks a lot

**Comment by machrisaa** [comment]
Hi @phongnhhn92, training the network from scratch is not in the scope of this project. But you may find something useful in the discussion [here](https://github.com/machrisaa/tensorflow-vgg/issues/14).
