### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by jhoh10** [machrisaa/tensorflow-vgg#28]
I am looking to fine tune the VGG19 model for an image classification problem, and am running into memory issues on my GPU.

I was wondering how much memory is expected to be used when training this network? When running it on a K80 with a 11 gb available, it was using 6.4 gb while training on just the two demo images.

I have heard of people running vgg19 on graphics cards with less than 4 gb of memory, so I was wondering if there room for improvement reducing the memory usage of this implementation?

**Comment by machrisaa** [comment]
Hi @jhoh10, my GPU only has 2GB and at most 1.8GB is available for training. I am afraid that the memory size cannot be reduced. But you may move some calculations to be calculated by the CPU and use the general memory instead. 

The bottleneck is in the fully connected layers. In most of my project that using the VGG, when I found the GPU memory issue, I will add `with tf.device('/cpu:0'):` to [the largest layer](https://github.com/machrisaa/tensorflow-vgg/blob/master/vgg19_trainable.py#L72) or even [the second largest layer](https://github.com/machrisaa/tensorflow-vgg/blob/master/vgg19_trainable.py#L79).

Hope that is it is helpful.
