### ISSUE TITLE
Which dataset is VGG_MEAN calculated from?

### ISSUE THREAD

**Issue by Evan-Gao** [machrisaa/tensorflow-vgg#29]
I want to use existing pre-trained weights to estimate top1/5 error of this model. Could you kindly tell me which dataset VGG_MEAN is calculated from?

**Comment by machrisaa** [comment]
Hi @Evan-Gao, that is a pre-processed mean pixels value from the training data set by the original author of VGG. You can find more detail in the [original implementation](https://gist.github.com/ksimonyan/3785162f95cd2d5fee77)
