### ISSUE TITLE
Training does not work

### ISSUE THREAD

**Issue by martin3000** [machrisaa/tensorflow-vgg#33]
I use test_vgg19_trainable to train the vgg19 net.
I feed a photo of a face (not tiger), telling the net it is a tiger (#292=1).
But in every run the system says it is a "cup" (#968) with p=1.

**Comment by machrisaa** [comment]
Hi @martin3000, it depends on how you train the network. Do you mind to let me have a look at your script that trains the network?

**Comment by martin3000** [comment]
Of course...have a look. I wonder that if I use test_vgg16.py or test_vgg19.py: the best result always has a probability of 1. I think there is something wrong.

[temp.txt](https://github.com/machrisaa/tensorflow-vgg/files/1057363/temp.txt)
