### ISSUE TITLE
NPYs are not available for downloading

### ISSUE THREAD

**Issue by chjiao** [machrisaa/tensorflow-vgg#34]
The two pre-trained models of npy files are not able to be downloaded.

**Comment by machrisaa** [comment]
The link on the Mega Drive is working fine. As far as I know, the [mega.nz](https://mega.nz/) was blocked in some countries. Can you open the link?

**Comment by fanyuzeng** [comment]
I can't download the npy files, what's wrong?

**Comment by fanyuzeng** [comment]
@machrisaa  Could you send me the available link. Many thanks to you. 
My email:  zengfanyu_cn@163.com

**Comment by machrisaa** [comment]
Hi @fanyuzeng , it is about 500MB and I don't think I can send it by email. On the other hand, will you have any cloud drive that I can upload to?
