### ISSUE TITLE
what is VGG_MEAN ?

### ISSUE THREAD

**Issue by jacobishao** [machrisaa/tensorflow-vgg#36]
when convert rgb to bgr ,why need to minus VGG_MEAN?

**Comment by machrisaa** [comment]
Hi @jacobishao, it is the pre-calculated mean used to normalise the data in the [original training](https://gist.github.com/ksimonyan/3785162f95cd2d5fee77).

**Comment by jacobishao** [comment]
oh！ thank you very much! I guess the mean is calculated from ImageNet,right?

2017-07-17 21:36 GMT+08:00 Chris <notifications@github.com>:
