### ISSUE TITLE
What database did this vgg implementation trained on?

### ISSUE THREAD

**Issue by azure-crab** [machrisaa/tensorflow-vgg#38]
Hi,

I'm using this library to do some research, and it will be a great help if I can know which database was the model trained on. If it is Imagenet, what's the version of the data from Imagenet, is it ILSVRC2012 or ILSVRC2014?
Thanks.

Wanquan,

**Comment by machrisaa** [comment]
Hi @azure-crab, from the [original implementation](https://gist.github.com/ksimonyan/3785162f95cd2d5fee77), it was trained with the  ILSVRC2014 dataset.
