### ISSUE TITLE
why we devide image by 255.0?

### ISSUE THREAD

**Issue by chunhui204** [machrisaa/tensorflow-vgg#47]

**Comment by deng-wei** [comment]
Take a look at vgg19.py~

**Comment by chunhui204** [comment]
I know the image multiplied by 255.0, but i dont know meaning of deviding image and then multipling it,thanks so much

**Comment by chunhui204** [comment]
I know, its data normalization! Forgive my stupid please...

**Comment by alexwongdl** [comment]
I have the same question, `img = img / 255.0` and then `rgb_scaled = rgb * 255.0`, does not do any normalization between them.
