### ISSUE TITLE
The conv kernel is 1*1. It's different with the conv kernel in the paper which is 3*3. It's something wrong. Thanks for your answer

### ISSUE THREAD

**Issue by miraclewxl** [machrisaa/tensorflow-vgg#52]
The size of kernel in convolutional lay is 1*1. However the size of kernel in convolutional lay in the paper which is 3*3. It's something wrong. Thanks for your answer

**Comment by machrisaa** [comment]
All the weight in the conv layers are all 3 by 3:
```
 filt, conv_biases = self.get_conv_var(3, in_channels, out_channels, name)
```
