### ISSUE TITLE
_pickle.UnpicklingError

### ISSUE THREAD

**Issue by baiyigali** [machrisaa/tensorflow-vgg#62]
when loading vgg16.npy i occurred: _pickle.UnpicklingError, but the vgg19.npy loaded successfully, i suspect the vgg16.npy you provided is corrupted, could you provide some kind of checksum?

**Comment by machrisaa** [comment]
I have just tested to download the vgg16.npy file and it is fine. The shasum is `6206897b35c2bfe5d9d16b83314e44fc3ea83b1c`
