### ISSUE TITLE
VGG Numpy files distribution.

### ISSUE THREAD

**Issue by janivanecky** [machrisaa/tensorflow-vgg#8]
Hi Chris,
I've used your TF implementation of VGGnet in my [project](https://github.com/janivanecky/Artistic-Style) and linked your dropbox storage to download the numpy file. However, it looks like the link was disabled due to too much traffic. Would it be alright if I reuploaded it somewhere and linked there?

Thanks,
Jan

**Comment by machrisaa** [comment]
Thanks Jan. I got the notice from dropbox this morning as well. I am trying to upload it to [mega](mega.nz). I will update the link ASAP once it is done.

**Comment by machrisaa** [comment]
Hi Jan. The links have been updated.

**Comment by janivanecky** [comment]
Thanks Chris.
